{
    'name': 'Procurement App',
    'version': '1.0',
    'summary': 'Manage Requisitions and Automate RFQ, PO, Invoice, and GRV creation',
    'description': 'Custom Requisition app that perfectly integrates with Odoo Purchase, Inventory, and Invoicing.',
    'author': 'Antigravity',
    'depends': ['base', 'purchase', 'stock', 'account', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'wizard/create_rfq_wizard_views.xml',
        'wizard/create_supplier_quote_wizard_views.xml',
        'views/material_requisition_views.xml',
        'views/custom_purchase_order_views.xml',
        'views/custom_purchase_invoice_views.xml',
        'views/custom_supplier_quote_views.xml',
        'views/custom_grv_views.xml',
        'views/custom_rfq_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
